{
	"version": 1591946542,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/main-sheet0.png",
		"images/menu_utama-sheet0.png",
		"images/teks-sheet0.png",
		"images/bubble-sheet0.png",
		"images/asset1xxxhdpi-sheet0.png",
		"images/particles.png",
		"images/bombsea2-sheet0.png",
		"images/landaklaut-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite3-sheet2.png",
		"images/sprite3-sheet3.png",
		"images/sprite3-sheet4.png",
		"images/sprite3-sheet5.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/yourscore-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/scoreboard-sheet0.png",
		"images/gtame_over-sheet0.png",
		"images/play-sheet0.png",
		"images/exit-sheet0.png",
		"images/bglaut-sheet0.png",
		"images/bglaut2-sheet0.png",
		"images/bgfix-sheet0.png",
		"images/bubblefix-sheet0.png",
		"images/bubblefix2-sheet0.png",
		"media/bubble sound.m4a",
		"media/bubble sound.ogg",
		"media/bomb+1.m4a",
		"media/bomb+1.ogg",
		"media/aw sfx.m4a",
		"media/aw sfx.ogg",
		"media/data--beep--chirp--low-tech-sound-effect-84539795_01.m4a",
		"media/data--beep--chirp--low-tech-sound-effect-84539795_01.ogg",
		"media/collect-bonus-sound-effect-82293702_01.m4a",
		"media/collect-bonus-sound-effect-82293702_01.ogg",
		"media/ding - sound effects youtube.m4a",
		"media/ding - sound effects youtube.ogg",
		"media/lid--plastic--small--pop-off-sound-effect-66900635_01.m4a",
		"media/lid--plastic--small--pop-off-sound-effect-66900635_01.ogg",
		"media/fun-times_looping_01.m4a",
		"media/fun-times_looping_01.ogg",
		"media/one-world_01.m4a",
		"media/one-world_01.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}